# dockerfile to build cmake cpp
FROM ubuntu:latest

# Install cmake
RUN apt-get update
RUN apt-get install -y g++
RUN apt-get install -y make
RUN apt-get install -y cmake

# sctp-dev
RUN apt-get install -y libsctp-dev

# Copy the current directory contents into the container at /app
COPY . /app

# Set the working directory to /app
WORKDIR /app

# Build the project
RUN make

# Run the executable
CMD ["./hello"]